language: cpp

matrix:
    include:
        - os: linux
          dist: xenial
          sudo: false
          compiler: gcc
          addons:
            apt:
              packages:
                - qt5-default
                - qtbase5-dev-tools
                - qt5-qmake
                - libtag1-dev
        - os: osx
          osx_image: xcode11.3
          compiler: clang

before_install:
    - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
        brew update;
      fi

install:
    - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
        brew update;
        brew install qt5;
        brew link --force qt5;
        brew install taglib;
        brew install create-dmg;
      fi

before_script:

script:
    - cd src && qmake UltraStar-Creator.pro && make -j4
    - cd ../bin/release
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then
        if [ -r "UltraStar-Creator.app" ]; then
            macdeployqt UltraStar-Creator.app -dmg;
            link=$(curl --upload-file 'UltraStar-Creator.dmg' "https://transfer.sh/UltraStar-Creator-$(git rev-parse --short HEAD).dmg");
            echo "UltraStar-Creator.dmg should be available at:";
            echo "    $link";
        fi
      fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
        if [ -r "UltraStar-Creator" ]; then
          cp ../../setup/unix/UltraStar-Creator.png .;
          cp ../../setup/unix/UltraStar-Creator.desktop .;
          cp ../../setup/unix/qt.conf .;
          cd ..;
          wget -c "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage";
          chmod a+x linuxdeployqt*.AppImage;
          unset QTDIR; unset QT_PLUGIN_PATH ; unset LD_LIBRARY_PATH;
          ./linuxdeployqt*.AppImage ./release/UltraStar-Creator.desktop -bundle-non-qt-libs;
          ./linuxdeployqt*.AppImage ./release/UltraStar-Creator.desktop -appimage;
          link=$(curl --upload-file *.AppImage "https://transfer.sh/UltraStar-Creator-$(git rev-parse --short HEAD)-x86_64.AppImage");
          echo "UltraStar-Creator.AppImage should be available at:";
          echo "    $link";
        fi
      fi

notifications:
    email: false
